# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import isac_pb2 as isac__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in isac_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ForwardFrame = channel.unary_unary(
                '/isac.IngestionService/ForwardFrame',
                request_serializer=isac__pb2.CSIFrame.SerializeToString,
                response_deserializer=isac__pb2.Ack.FromString,
                _registered_method=True)


class IngestionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ForwardFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ForwardFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardFrame,
                    request_deserializer=isac__pb2.CSIFrame.FromString,
                    response_serializer=isac__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isac.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('isac.IngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ForwardFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isac.IngestionService/ForwardFrame',
            isac__pb2.CSIFrame.SerializeToString,
            isac__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PreprocessingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFrame = channel.unary_unary(
                '/isac.PreprocessingService/ProcessFrame',
                request_serializer=isac__pb2.CSIFrame.SerializeToString,
                response_deserializer=isac__pb2.PreprocessedFrame.FromString,
                _registered_method=True)


class PreprocessingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreprocessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFrame,
                    request_deserializer=isac__pb2.CSIFrame.FromString,
                    response_serializer=isac__pb2.PreprocessedFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isac.PreprocessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('isac.PreprocessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreprocessingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isac.PreprocessingService/ProcessFrame',
            isac__pb2.CSIFrame.SerializeToString,
            isac__pb2.PreprocessedFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InferenceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/isac.InferenceService/Detect',
                request_serializer=isac__pb2.PreprocessedFrame.SerializeToString,
                response_deserializer=isac__pb2.DetectionResult.FromString,
                _registered_method=True)


class InferenceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=isac__pb2.PreprocessedFrame.FromString,
                    response_serializer=isac__pb2.DetectionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isac.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('isac.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isac.InferenceService/Detect',
            isac__pb2.PreprocessedFrame.SerializeToString,
            isac__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OutputServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreResult = channel.unary_unary(
                '/isac.OutputService/StoreResult',
                request_serializer=isac__pb2.DetectionResult.SerializeToString,
                response_deserializer=isac__pb2.Empty.FromString,
                _registered_method=True)
        self.GetResultStream = channel.unary_stream(
                '/isac.OutputService/GetResultStream',
                request_serializer=isac__pb2.Empty.SerializeToString,
                response_deserializer=isac__pb2.DetectionResult.FromString,
                _registered_method=True)


class OutputServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StoreResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResultStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OutputServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreResult': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreResult,
                    request_deserializer=isac__pb2.DetectionResult.FromString,
                    response_serializer=isac__pb2.Empty.SerializeToString,
            ),
            'GetResultStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetResultStream,
                    request_deserializer=isac__pb2.Empty.FromString,
                    response_serializer=isac__pb2.DetectionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isac.OutputService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('isac.OutputService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OutputService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isac.OutputService/StoreResult',
            isac__pb2.DetectionResult.SerializeToString,
            isac__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResultStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/isac.OutputService/GetResultStream',
            isac__pb2.Empty.SerializeToString,
            isac__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClockSyncServiceStub:
    """Runs alongside OutputService on the central node. Simulator (phone) probes this
    directly, bypassing the pipeline, to estimate phone<->server clock offset — the
    e2e latency metric subtracts request.timestamp_ns (phone clock) from time.time_ns()
    (server clock), so the offset must be measured out-of-band and published, not derived
    from the pipeline's own traffic.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Probe = channel.unary_unary(
                '/isac.ClockSyncService/Probe',
                request_serializer=isac__pb2.ClockProbe.SerializeToString,
                response_deserializer=isac__pb2.ClockProbe.FromString,
                _registered_method=True)


class ClockSyncServiceServicer:
    """Runs alongside OutputService on the central node. Simulator (phone) probes this
    directly, bypassing the pipeline, to estimate phone<->server clock offset — the
    e2e latency metric subtracts request.timestamp_ns (phone clock) from time.time_ns()
    (server clock), so the offset must be measured out-of-band and published, not derived
    from the pipeline's own traffic.
    """

    def Probe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClockSyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Probe': grpc.unary_unary_rpc_method_handler(
                    servicer.Probe,
                    request_deserializer=isac__pb2.ClockProbe.FromString,
                    response_serializer=isac__pb2.ClockProbe.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'isac.ClockSyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('isac.ClockSyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClockSyncService:
    """Runs alongside OutputService on the central node. Simulator (phone) probes this
    directly, bypassing the pipeline, to estimate phone<->server clock offset — the
    e2e latency metric subtracts request.timestamp_ns (phone clock) from time.time_ns()
    (server clock), so the offset must be measured out-of-band and published, not derived
    from the pipeline's own traffic.
    """

    @staticmethod
    def Probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/isac.ClockSyncService/Probe',
            isac__pb2.ClockProbe.SerializeToString,
            isac__pb2.ClockProbe.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
