# Local preview: `cd docs && bundle install && bundle exec jekyll serve`
# The GitHub Actions workflow (.github/workflows/docs.yml) builds this same Gemfile.
source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"

gem "webrick", "~> 1.8"
