apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: isac-pipeline
  namespace: isac-sensing
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: simulator
      toPorts:
        - ports:
            - port: "50051"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app: ingestion
      toPorts:
        - ports:
            - port: "50052"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app: preprocessing
      toPorts:
        - ports:
            - port: "50053"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app: inference
        - matchLabels:
            app: simulator
      toPorts:
        - ports:
            - port: "50054"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app: prometheus
            k8s:io.kubernetes.pod.namespace: isac-monitoring
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
            - port: "8001"
              protocol: TCP
            - port: "8002"
              protocol: TCP
            - port: "8003"
              protocol: TCP
            - port: "8004"
              protocol: TCP
  egress:
    - toEntities:
        - cluster
